### ISSUE TITLE
Missing variable check for tools.check_temporal_drift()

### ISSUE THREAD

**Issue by eleanorfrajka** [callumrollo/glidertest#52]
As in tools.optics_first_check.

I ran with a dataset that doesn't have CHLA, and it fell over.

**Comment by eleanorfrajka** [comment]
Actually, tools.plot_section_with_srss also fell over, but only after it looked like it was doing some work.

**Comment by callumrollo** [comment]
I'm working on adding these checks to all functions. I believe it would be best that the functions raise an Error when passed a dataset that does not contain an essential variable, rather than printing a statement and returning. This will make it clear to users that the function does not work without the requisite data variable. It's also good to fail fast, rather than do work before breaking later
